# Generated by Django 4.1.3 on 2022-11-25 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vania_art_studio.account.validators


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_appuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[vania_art_studio.account.validators.username_validator]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
