# Generated by Django 4.1.3 on 2022-11-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='product_type',
            field=models.TextField(default='album'),
        ),
        migrations.AddField(
            model_name='card',
            name='product_type',
            field=models.TextField(default='card'),
        ),
        migrations.AddField(
            model_name='christeningset',
            name='product_type',
            field=models.TextField(default='christening_set'),
        ),
        migrations.AddField(
            model_name='frame',
            name='product_type',
            field=models.TextField(default='frame'),
        ),
    ]
