# Generated by Django 4.1.3 on 2022-11-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_album_product_type_card_product_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='card',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='christeningset',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='product_type',
        ),
    ]
