# Generated by Django 4.1.3 on 2022-12-02 19:43

from django.db import migrations, models
import vania_art_studio.products.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_album_product_type_remove_card_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(validators=[vania_art_studio.products.validators.description_validator]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(validators=[vania_art_studio.products.validators.price_validator]),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(validators=[vania_art_studio.products.validators.quantity_validator]),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('male', 'Мъжки продукт'), ('female', 'Женски продукт')], max_length=6),
        ),
    ]
