# Generated by Django 4.1.3 on 2022-12-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_description_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
