# Generated by Django 4.1.3 on 2022-12-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_shoppingcart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
