# Generated by Django 4.1.3 on 2022-12-08 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_comments_commentator_alter_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='commentator',
            new_name='commentator_id',
        ),
    ]
